# Generated by Django 5.2.5 on 2025-09-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_businesscard'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards/'),
        ),
    ]
